/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan44_menu;

/**
 *
 * @author LENOVO
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama1
     */
    public utama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MASTER = new javax.swing.JMenu();
        PRODI = new javax.swing.JMenuItem();
        MATAKULIAH = new javax.swing.JMenuItem();
        DOSEN = new javax.swing.JMenuItem();
        CETAK_NAMA = new javax.swing.JMenuItem();
        APLIKASI_HOTEL = new javax.swing.JMenuItem();
        AJUAN = new javax.swing.JMenu();
        JADWAL = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MASTER.setText("Master");

        PRODI.setText("Prodi");
        PRODI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODIActionPerformed(evt);
            }
        });
        MASTER.add(PRODI);

        MATAKULIAH.setText("Mata Kuliah");
        MASTER.add(MATAKULIAH);

        DOSEN.setText("Dosen");
        MASTER.add(DOSEN);

        CETAK_NAMA.setText("Cetak Nama");
        CETAK_NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETAK_NAMAActionPerformed(evt);
            }
        });
        MASTER.add(CETAK_NAMA);

        APLIKASI_HOTEL.setText("Aplikasi Hotel");
        APLIKASI_HOTEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APLIKASI_HOTELActionPerformed(evt);
            }
        });
        MASTER.add(APLIKASI_HOTEL);

        jMenuBar1.add(MASTER);

        AJUAN.setText("Ajuan");
        jMenuBar1.add(AJUAN);

        JADWAL.setText("Jadwal");
        jMenuBar1.add(JADWAL);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRODIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODIActionPerformed
        // TODO add your handling code here:
        Prodi1 p = new Prodi1();
        p.setVisible(true);
        
    }//GEN-LAST:event_PRODIActionPerformed

    private void CETAK_NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETAK_NAMAActionPerformed
        // TODO add your handling code here:
         cCetakNama cetaknama = new cCetakNama();
        cetaknama.setVisible(true);
    }//GEN-LAST:event_CETAK_NAMAActionPerformed

    private void APLIKASI_HOTELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APLIKASI_HOTELActionPerformed
        // TODO add your handling code here:
        cAplikasiHotel aplikasihotel = new cAplikasiHotel();
        aplikasihotel.setVisible(true);
    }//GEN-LAST:event_APLIKASI_HOTELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AJUAN;
    private javax.swing.JMenuItem APLIKASI_HOTEL;
    private javax.swing.JMenuItem CETAK_NAMA;
    private javax.swing.JMenuItem DOSEN;
    private javax.swing.JMenu JADWAL;
    private javax.swing.JMenu MASTER;
    private javax.swing.JMenuItem MATAKULIAH;
    private javax.swing.JMenuItem PRODI;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
